name: healthcheck_service

on:
    push:
        branches:
            - master

jobs:
    health check:
        runs-on: ubuntu-latest
        uses: jtalk/url-health-check-action@v3
        with:
            url: https://heroku-pokedex-app.herokuapp.com/
            follow-redirect: false
            max-atempts: 3
            retry-delay: 5s
            retry-all: false
